# Generated by Django 5.2.18 on 2026-10-07 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
        ('notifications', '0007_central_email_recipients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertrule',
            name='signal',
            field=models.CharField(choices=[('DOCUMENT_UPLOADED', 'Document uploaded'), ('INVOICE_RECORDED', 'Invoice recorded'), ('PAYMENT_RECORDED', 'Payment recorded'), ('AUTOMATION_FAILURE', 'Automation failure'), ('RENEWAL_DUE', 'Renewal due'), ('EXPENSE_APPROVAL', 'Expense approval'), ('REIMBURSEMENT_APPROVAL', 'Reimbursement approval'), ('BUDGET_THRESHOLD', 'Budget threshold'), ('MISSING_INVOICE', 'Missing invoice'), ('INVOICE_OVERDUE', 'Invoice overdue'), ('RECONCILIATION_NEEDED', 'Reconciliation needed'), ('SYSTEM', 'System')], max_length=32),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='signal',
            field=models.CharField(blank=True, choices=[('DOCUMENT_UPLOADED', 'Document uploaded'), ('INVOICE_RECORDED', 'Invoice recorded'), ('PAYMENT_RECORDED', 'Payment recorded'), ('AUTOMATION_FAILURE', 'Automation failure'), ('RENEWAL_DUE', 'Renewal due'), ('EXPENSE_APPROVAL', 'Expense approval'), ('REIMBURSEMENT_APPROVAL', 'Reimbursement approval'), ('BUDGET_THRESHOLD', 'Budget threshold'), ('MISSING_INVOICE', 'Missing invoice'), ('INVOICE_OVERDUE', 'Invoice overdue'), ('RECONCILIATION_NEEDED', 'Reconciliation needed'), ('SYSTEM', 'System')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='emailtemplateversion',
            name='signal',
            field=models.CharField(blank=True, choices=[('DOCUMENT_UPLOADED', 'Document uploaded'), ('INVOICE_RECORDED', 'Invoice recorded'), ('PAYMENT_RECORDED', 'Payment recorded'), ('AUTOMATION_FAILURE', 'Automation failure'), ('RENEWAL_DUE', 'Renewal due'), ('EXPENSE_APPROVAL', 'Expense approval'), ('REIMBURSEMENT_APPROVAL', 'Reimbursement approval'), ('BUDGET_THRESHOLD', 'Budget threshold'), ('MISSING_INVOICE', 'Missing invoice'), ('INVOICE_OVERDUE', 'Invoice overdue'), ('RECONCILIATION_NEEDED', 'Reconciliation needed'), ('SYSTEM', 'System')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('DOCUMENT_UPLOADED', 'Document uploaded'), ('INVOICE_RECORDED', 'Invoice recorded'), ('PAYMENT_RECORDED', 'Payment recorded'), ('AUTOMATION_FAILURE', 'Automation failure'), ('RENEWAL_DUE', 'Renewal due'), ('EXPENSE_APPROVAL', 'Expense approval'), ('REIMBURSEMENT_APPROVAL', 'Reimbursement approval'), ('BUDGET_THRESHOLD', 'Budget threshold'), ('MISSING_INVOICE', 'Missing invoice'), ('INVOICE_OVERDUE', 'Invoice overdue'), ('RECONCILIATION_NEEDED', 'Reconciliation needed'), ('SYSTEM', 'System')], max_length=32),
        ),
        migrations.AlterField(
            model_name='notificationdelivery',
            name='legal_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notification_deliveries', to='identity.legalentity'),
        ),
        migrations.AlterField(
            model_name='notificationdelivery',
            name='signal',
            field=models.CharField(choices=[('DOCUMENT_UPLOADED', 'Document uploaded'), ('INVOICE_RECORDED', 'Invoice recorded'), ('PAYMENT_RECORDED', 'Payment recorded'), ('AUTOMATION_FAILURE', 'Automation failure'), ('RENEWAL_DUE', 'Renewal due'), ('EXPENSE_APPROVAL', 'Expense approval'), ('REIMBURSEMENT_APPROVAL', 'Reimbursement approval'), ('BUDGET_THRESHOLD', 'Budget threshold'), ('MISSING_INVOICE', 'Missing invoice'), ('INVOICE_OVERDUE', 'Invoice overdue'), ('RECONCILIATION_NEEDED', 'Reconciliation needed'), ('SYSTEM', 'System')], default='RENEWAL_DUE', max_length=32),
        ),
    ]
