import decimal
import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounting", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=180)),
                ("contact_name", models.CharField(blank=True, max_length=160)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("tax_id", models.CharField(blank=True, max_length=80)),
                ("payment_terms_days", models.PositiveSmallIntegerField(default=0)),
                ("status", models.CharField(choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")], default="ACTIVE", max_length=16)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("default_expense_account", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="default_for_vendors", to="accounting.account")),
                ("legal_entity", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="vendors", to="identity.legalentity")),
                ("payable_account", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="payable_for_vendors", to="accounting.account")),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="FinancialAccount",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=180)),
                ("account_type", models.CharField(choices=[("BANK", "Bank"), ("CASH", "Cash"), ("CREDIT_CARD", "Credit card"), ("WALLET", "Wallet"), ("PAYMENT_PROCESSOR", "Payment processor")], max_length=24)),
                ("currency", models.CharField(max_length=3)),
                ("institution_name", models.CharField(blank=True, max_length=180)),
                ("last_four", models.CharField(blank=True, max_length=4)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ledger_account", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="financial_account", to="accounting.account")),
                ("legal_entity", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="financial_accounts", to="identity.legalentity")),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("expense_date", models.DateField()),
                ("due_date", models.DateField(blank=True, null=True)),
                ("description", models.CharField(max_length=255)),
                ("reference", models.CharField(blank=True, max_length=120)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("tax_amount", models.DecimalField(decimal_places=2, default=decimal.Decimal("0"), max_digits=20)),
                ("currency", models.CharField(max_length=3)),
                ("fx_rate", models.DecimalField(decimal_places=10, default=decimal.Decimal("1"), max_digits=20)),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("SUBMITTED", "Submitted"), ("APPROVED", "Approved"), ("REJECTED", "Rejected"), ("PARTIALLY_PAID", "Partially paid"), ("PAID", "Paid")], default="DRAFT", max_length=20)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="approved_expenses", to=settings.AUTH_USER_MODEL)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_expenses", to=settings.AUTH_USER_MODEL)),
                ("expense_account", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="expenses", to="accounting.account")),
                ("journal_entry", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="expense", to="accounting.journalentry")),
                ("legal_entity", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="expenses", to="identity.legalentity")),
                ("payable_account", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="expense_payables", to="accounting.account")),
                ("rejected_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="rejected_expenses", to=settings.AUTH_USER_MODEL)),
                ("tax_code", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="expenses", to="accounting.taxcode")),
                ("vendor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="expenses", to="finance.vendor")),
            ],
            options={"ordering": ["-expense_date", "-created_at"]},
        ),
        migrations.CreateModel(
            name="Income",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("income_date", models.DateField()),
                ("payer_name", models.CharField(blank=True, max_length=180)),
                ("description", models.CharField(max_length=255)),
                ("reference", models.CharField(blank=True, max_length=120)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("currency", models.CharField(max_length=3)),
                ("fx_rate", models.DecimalField(decimal_places=10, default=decimal.Decimal("1"), max_digits=20)),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("POSTED", "Posted")], default="DRAFT", max_length=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_income_records", to=settings.AUTH_USER_MODEL)),
                ("financial_account", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="income_records", to="finance.financialaccount")),
                ("journal_entry", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="income_record", to="accounting.journalentry")),
                ("legal_entity", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="income_records", to="identity.legalentity")),
                ("revenue_account", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="income_records", to="accounting.account")),
            ],
            options={"ordering": ["-income_date", "-created_at"]},
        ),
        migrations.CreateModel(
            name="Transfer",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("transfer_date", models.DateField()),
                ("source_amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("destination_amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("source_fx_rate", models.DecimalField(decimal_places=10, default=decimal.Decimal("1"), max_digits=20)),
                ("destination_fx_rate", models.DecimalField(decimal_places=10, default=decimal.Decimal("1"), max_digits=20)),
                ("reference", models.CharField(blank=True, max_length=120)),
                ("memo", models.CharField(blank=True, max_length=255)),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("POSTED", "Posted")], default="DRAFT", max_length=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_transfers", to=settings.AUTH_USER_MODEL)),
                ("from_account", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="outgoing_transfers", to="finance.financialaccount")),
                ("journal_entry", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="transfer", to="accounting.journalentry")),
                ("legal_entity", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="transfers", to="identity.legalentity")),
                ("to_account", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="incoming_transfers", to="finance.financialaccount")),
            ],
            options={"ordering": ["-transfer_date", "-created_at"]},
        ),
        migrations.CreateModel(
            name="FounderFunding",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("funding_date", models.DateField()),
                ("founder_name", models.CharField(max_length=180)),
                ("funding_type", models.CharField(choices=[("CONTRIBUTION", "Founder contribution"), ("LOAN", "Founder loan")], max_length=16)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("currency", models.CharField(max_length=3)),
                ("fx_rate", models.DecimalField(decimal_places=10, default=decimal.Decimal("1"), max_digits=20)),
                ("reference", models.CharField(blank=True, max_length=120)),
                ("memo", models.CharField(blank=True, max_length=255)),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("POSTED", "Posted")], default="DRAFT", max_length=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("counter_account", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="founder_funding", to="accounting.account")),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_founder_funding", to=settings.AUTH_USER_MODEL)),
                ("financial_account", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="founder_funding", to="finance.financialaccount")),
                ("journal_entry", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="founder_funding", to="accounting.journalentry")),
                ("legal_entity", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="founder_funding", to="identity.legalentity")),
            ],
            options={"ordering": ["-funding_date", "-created_at"]},
        ),
        migrations.CreateModel(
            name="Reimbursement",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("expense_date", models.DateField()),
                ("description", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("currency", models.CharField(max_length=3)),
                ("fx_rate", models.DecimalField(decimal_places=10, default=decimal.Decimal("1"), max_digits=20)),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("SUBMITTED", "Submitted"), ("APPROVED", "Approved"), ("REJECTED", "Rejected"), ("PARTIALLY_PAID", "Partially paid"), ("PAID", "Paid")], default="DRAFT", max_length=20)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="approved_reimbursements", to=settings.AUTH_USER_MODEL)),
                ("claimant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="reimbursements", to=settings.AUTH_USER_MODEL)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_reimbursements", to=settings.AUTH_USER_MODEL)),
                ("expense_account", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="reimbursements", to="accounting.account")),
                ("journal_entry", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="reimbursement", to="accounting.journalentry")),
                ("legal_entity", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="reimbursements", to="identity.legalentity")),
                ("payable_account", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="reimbursement_payables", to="accounting.account")),
                ("rejected_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="rejected_reimbursements", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-expense_date", "-created_at"]},
        ),
        migrations.CreateModel(
            name="ApprovalAction",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("object_type", models.CharField(choices=[("EXPENSE", "Expense"), ("REIMBURSEMENT", "Reimbursement")], max_length=20)),
                ("object_id", models.UUIDField()),
                ("action", models.CharField(choices=[("SUBMITTED", "Submitted"), ("APPROVED", "Approved"), ("REJECTED", "Rejected")], max_length=16)),
                ("comment", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("actor", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="finance_approval_actions", to=settings.AUTH_USER_MODEL)),
                ("legal_entity", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="finance_approval_actions", to="identity.legalentity")),
            ],
            options={"ordering": ["created_at"]},
        ),
        migrations.CreateModel(
            name="ExpensePayment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("payment_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("currency", models.CharField(max_length=3)),
                ("fx_rate", models.DecimalField(decimal_places=10, default=decimal.Decimal("1"), max_digits=20)),
                ("base_amount", models.DecimalField(decimal_places=2, default=decimal.Decimal("0"), max_digits=20)),
                ("reference", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_expense_payments", to=settings.AUTH_USER_MODEL)),
                ("expense", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payments", to="finance.expense")),
                ("financial_account", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="expense_payments", to="finance.financialaccount")),
                ("journal_entry", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="expense_payment", to="accounting.journalentry")),
                ("legal_entity", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="expense_payments", to="identity.legalentity")),
            ],
            options={"ordering": ["-payment_date", "-created_at"]},
        ),
        migrations.CreateModel(
            name="ReimbursementPayment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("payment_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("currency", models.CharField(max_length=3)),
                ("fx_rate", models.DecimalField(decimal_places=10, default=decimal.Decimal("1"), max_digits=20)),
                ("base_amount", models.DecimalField(decimal_places=2, default=decimal.Decimal("0"), max_digits=20)),
                ("reference", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_reimbursement_payments", to=settings.AUTH_USER_MODEL)),
                ("financial_account", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="reimbursement_payments", to="finance.financialaccount")),
                ("journal_entry", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="reimbursement_payment", to="accounting.journalentry")),
                ("legal_entity", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="reimbursement_payments", to="identity.legalentity")),
                ("reimbursement", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payments", to="finance.reimbursement")),
            ],
            options={"ordering": ["-payment_date", "-created_at"]},
        ),
        migrations.CreateModel(
            name="FinanceDocument",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("document_type", models.CharField(choices=[("RECEIPT", "Receipt"), ("INVOICE", "Invoice"), ("BILL", "Bill"), ("STATEMENT", "Statement"), ("OTHER", "Other")], max_length=16)),
                ("file", models.FileField(upload_to="finance/%Y/%m/")),
                ("original_name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expense", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="documents", to="finance.expense")),
                ("founder_funding", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="documents", to="finance.founderfunding")),
                ("income", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="documents", to="finance.income")),
                ("legal_entity", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="finance_documents", to="identity.legalentity")),
                ("reimbursement", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="documents", to="finance.reimbursement")),
                ("transfer", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="documents", to="finance.transfer")),
                ("uploaded_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="uploaded_finance_documents", to=settings.AUTH_USER_MODEL)),
                ("vendor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="documents", to="finance.vendor")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddConstraint(
            model_name="vendor",
            constraint=models.UniqueConstraint(fields=("legal_entity", "code"), name="uniq_vendor_code_per_entity"),
        ),
        migrations.AddConstraint(
            model_name="financialaccount",
            constraint=models.UniqueConstraint(fields=("legal_entity", "name"), name="uniq_financial_account_name_per_entity"),
        ),
    ]
