from django.urls import path

from .views import (
    BillingDashboardView,
    BillingPaymentAllocationView,
    BillingPaymentDetailView,
    BillingPaymentListCreateView,
    BillingPeriodDetailView,
    BillingPeriodListCreateView,
    RenewalCalendarView,
    ServiceAccountDetailView,
    ServiceAccountListCreateView,
    SubscriptionDetailView,
    SubscriptionListCreateView,
    SubscriptionInvoiceDetailView,
    SubscriptionInvoiceListCreateView,
    SubscriptionInvoiceVoidView,
    SubscriptionMarkPaidView,
    SubscriptionPaymentHistoryView,
    VendorServiceDetailView,
    VendorServiceListCreateView,
)

urlpatterns = [
    path(
        "operations/billing/summary/",
        BillingDashboardView.as_view(),
        name="billing-dashboard",
    ),
    path(
        "operations/billing/periods/",
        BillingPeriodListCreateView.as_view(),
        name="billing-period-list",
    ),
    path(
        "operations/billing/periods/<uuid:object_id>/",
        BillingPeriodDetailView.as_view(),
        name="billing-period-detail",
    ),
    path(
        "operations/billing/invoices/",
        SubscriptionInvoiceListCreateView.as_view(),
        name="subscription-invoice-list",
    ),
    path(
        "operations/billing/invoices/<uuid:object_id>/",
        SubscriptionInvoiceDetailView.as_view(),
        name="subscription-invoice-detail",
    ),
    path(
        "operations/billing/invoices/<uuid:object_id>/void/",
        SubscriptionInvoiceVoidView.as_view(),
        name="subscription-invoice-void",
    ),
    path(
        "operations/billing/payments/",
        BillingPaymentListCreateView.as_view(),
        name="billing-payment-list",
    ),
    path(
        "operations/billing/payments/<uuid:object_id>/",
        BillingPaymentDetailView.as_view(),
        name="billing-payment-detail",
    ),
    path(
        "operations/billing/payments/<uuid:object_id>/allocations/",
        BillingPaymentAllocationView.as_view(),
        name="billing-payment-allocations",
    ),
    path(
        "operations/vendor-services/",
        VendorServiceListCreateView.as_view(),
        name="vendor-service-list",
    ),
    path(
        "operations/vendor-services/<uuid:object_id>/",
        VendorServiceDetailView.as_view(),
        name="vendor-service-detail",
    ),
    path(
        "operations/service-accounts/",
        ServiceAccountListCreateView.as_view(),
        name="service-account-list",
    ),
    path(
        "operations/service-accounts/<uuid:object_id>/",
        ServiceAccountDetailView.as_view(),
        name="service-account-detail",
    ),
    path(
        "operations/subscriptions/",
        SubscriptionListCreateView.as_view(),
        name="subscription-list",
    ),
    path(
        "operations/subscriptions/<uuid:object_id>/",
        SubscriptionDetailView.as_view(),
        name="subscription-detail",
    ),
    path(
        "operations/subscriptions/<uuid:object_id>/payments/",
        SubscriptionPaymentHistoryView.as_view(),
        name="subscription-payment-history",
    ),
    path(
        "operations/subscriptions/<uuid:object_id>/mark-paid/",
        SubscriptionMarkPaidView.as_view(),
        name="subscription-mark-paid",
    ),
    path("operations/renewals/", RenewalCalendarView.as_view(), name="renewal-calendar"),
]
